name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: |
          cd electron
          npm ci
      - name: Build
        run: |
          cd electron
          setx CSC_IDENTITY_AUTO_DISCOVERY false
          npm run dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: electron/dist/**
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            electron/dist/*.exe
            electron/dist/*.msi
            electron/dist/installer-output/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
